### PR TITLE
Missing tie in original.krn.

### PR DESCRIPTION
**Pull request by pkirlin**
This is the only one I noticed at a glance.

### CODE REVIEW

**Review by craigsapp — APPROVED** [review]

**Comment by craigsapp** [comment]
Note: updates to this repository will be mirrored on within an hour automatically onto kernScores and VHV.

Now you are going to make me look at the Original Rags to proofread it.  I do this in VHV:

https://verovio.humdrum.org/?file=joplin/original.krn

For the Joplin rags, the spacing of the notation needs to be widened so that the ties show properly (I do this by typing `alt-w` a few times to widen the spacing of the music.   Then for proofreading, I display the original scan with `alt-p`:

Screen Shot 2021-01-11 at 1 09 12 PM

Then I add in line-break markers to match the scan making it easier to coordinate the VHV notation and the scan, adding this just before the barline at the system brea:

```
!!LO:LB:g=z
```

`LO` meaning a layout parameter (which applies to the next non-null token in the spine, which would be the barline).  `LB` means it is a linebreak, and `g=z` is a parameter where `g` means "group" and `z` is the name of a group.  `z` does not really have any meaning, but in the future I will allow for different linebreak sets for different sources, so each source's line breaks can be encoded for redoing the layout for different editions.

Eventually I will get around to proofreading the notation for the Joplin data set (most pitches should be corrected, although missing ties are possible since I previously did proof listening in 2008 to get the pitches right for analysis.

**Comment by pkirlin** [comment]
Thanks for looking at this.  I'm using the joplin set to do some research on rhythm and syncopation, so if I find more errors, do you want me to make individual pull requests, or one big one at the end, or just email them to you?  :)  I don't want to make it seem like you have to correct these immediately.

**Comment by craigsapp** [comment]
Either way is good.  Probably the best is one submission for each work so that is easier to track the changes from the Github web interface.

Currently I am going through the Beethoven sonatas: 
https://github.com/craigsapp/beethoven-piano-sonatas/tree/master/kern

The commit note is useful for see which ones are left, and/or the last time I edited a particular file and roughly what I did to the file:

Screen Shot 2021-01-11 at 1 34 05 PM

**Comment by craigsapp** [comment]
I found four other notes in Original Rags that were missing ties, which are added in commit https://github.com/craigsapp/joplin/commit/e086f85044fd27ef0de57a84bcf309180b13601a

**Pull request closed without merging**
